### ISSUE TITLE
Does it works now?

### ISSUE THREAD

**Issue by JafferWilson** [ab/crackedin#1]
I have not tried your script yet as I would like to know whether it still works or not. Your script is 5 years old and I think if I try it now then I might get banned by linkedin.  
Can you tell me is there a safer way to get linked data of the people who are now live with the website?

**Comment by ab** [comment]
This data came from the original LinkedIn breach. It may not be useful today.

Not sure what your use case is, but for testing whether your own account is part of various breaches, I'd recommend https://haveibeenpwned.com/ — it includes the LinkedIn data among many other sites.

**Comment by JafferWilson** [comment]
Thank you for your recommendation. Glad to hear from you. :)
